### ISSUE TITLE
GDT 구현

### ISSUE THREAD

**Issue by 42mypark** [exciting-kfs/kfs#18]
요구사항 대로 GDT를 구현

1. GDT가 BIOS에 선언되어야 함.
2. GDT가 존재하는 address는 0x800이어야함.
3. GDT에 6개의 segment descriptor가 있어야함. (kernel, user) X (code, data, stack)

**Comment by 42mypark** [comment]
1 & 3

요구사항을 만족하기 위해 BIOS의 커스터마이징이 필요하므로, 현재 사용 중인 BIOS가 무엇인지 알아야함.

[qemu i440fx](https://www.qemu.org/docs/master/system/i386/pc.html?highlight=seabios)를 확인해보면 SeaBios를 사용 중임을 알 수 있다.

organization의 하나의 레포로 fork하여 수정을 진행.

**seabios/src/misc.c** 에 보면 BIOS에서 사용하는 GDT가 존재하여, 동일한 위치에 커널에서 사용할 GDT를 선언함.

**Comment by 42mypark** [comment]
2

 **src/post.c**의 startBoot함수에서 `int 0x19`를 호출하기 전에 0x7000 ~ 0x90000의 영역을 0으로 초기화하고 있다.

바로 아래 부분에 memcpy를 통해 BIOS에 선언한 GDT를 [0x800]에, gdtr을 [0x800 - 0x6]에 복사하였다.

`int 0x19` 끝난 이후에 복사하려했지만, 실행흐름이 bootloader로 넘어가서 불가능하였음.

**Comment by 42mypark** [comment]
@42-cjeon 

2번의 풀이 방식에 대해, 안전한 방식인지 논의가 필요할 듯 합니다. 

[Sea BIOS memory used at runtime](https://github.com/coreboot/seabios/blob/master/docs/Memory_Model.md#common-memory-used-at-run-time)를 보면, 0x800 근처 영역을 딱히 사용하지는 않습니다.

[OSdev MemoryMap](https://wiki.osdev.org/Memory_Map_(x86)#Real_mode_address_space_.28.3C_1_MiB.29)의 3번째 문단을 보면, 모든 BIOS function call 이후에, 메모리 0x500 이후 영역에 대해 다시 사용할 수 있다고 쓰여있습니다.

모든 BIOS function이 호출된 이후는 아니지만, Seabios에서 사용하지 않는 영역이므로 위와 같은 방식으로 코드를 작성해도 안전하다고 판단하였습니다.

어떻게 생각하시나요?

[GRUB2 BIOS-port-memory-map](https://www.gnu.org/software/grub/manual/grub-dev/html_node/BIOS-port-memory-map.html)에서도 딱히 0x800근처 영역을 수정하지 않는 것으로 보입니다.

**Comment by 42mypark** [comment]
위와 같은 방식으로 BIOS를 커스터마이징한 후에, qemu에서 bios를 설정해 주면 됩니다.

**Comment by 42-cjeon** [comment]
gdt 브랜치에서 적용되었습니다.
