### ISSUE TITLE
Slub allocator 구현

### ISSUE THREAD

**Issue by 42-cjeon** [exciting-kfs/kfs#36]
- [x] FreeList
- [x] ObjCache: for object allocation.
- [x] SizeCache: for `kmalloc`.
- [x] CacheManager: for cache shrinking

**Comment by 42mypark** [comment]
- [ ] FreeList
- [ ] ObjCache: for object allocation.
- [ ] SizeCache: for `kmalloc`.
- [ ] CacheManager: for cache shrinking

**Comment by 42mypark** [comment]
리눅스의 캐시 구현에 따라 객체를 할당해주는 software cache(ObjCache)를  구현했지만,

리눅스에서 자료구조를 구현하는 방식(객체를 할당하고 자료구조의 노드를 embeding하는 방식)과

러스트 collection에서 자료구조를 구현(allocator에서 객체를 하나씩 할당받는 방식)하는 방식이 달라서 

ObjCache가 굳이 필요하지 않을 것 같다는 결론을 내렸다.

ex) rust의 vector에 allocator를 따로 설정해준다고 해보자.

```
let v1: Vec<_, ObjCache<usize>> = ...;
let v2: Vec<_, ObjCache<usize>> = ...;
```

위와 같은 코드를 작성했다고 했을 때, 두 vector는 같은 ObjCache<usize> 인스턴스를 사용하는 것이 아니라, 서로 다른 인스턴스를 사용한다.

또, 인스턴스가 만들어지는 과정에서, CacheManager에 등록하려면 러스트 collection 코드를 수정해야한다.

**Comment by 42mypark** [comment]
- [ ] cpu local ?

**Comment by 42mypark** [comment]
cpu local software cahce가 과연 필요할까?

멀티 스레딩 환경에서, string이나 vector같이 임시로 쓰는 컨테이너 객체에 대해서 쓰면 성능 향상에 상당히 좋을 듯 싶다.
